plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id "com.github.ben-manes.versions" version "0.54.0"
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Portfolio site backend'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation'org.springframework.boot:spring-boot-starter-webmvc-test'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	testImplementation 'com.h2database:h2'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	runtimeOnly 'org.postgresql:postgresql'

	// Mybatis
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:4.0.1'

	// MapStruct
	implementation 'org.mapstruct:mapstruct:1.6.3'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

	// OpenAPI + Swagger
	implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3"

	// JWT
	implementation 'com.auth0:java-jwt:4.5.2'
	// パスワードハッシュ用
	implementation 'org.springframework.security:spring-security-crypto'

	// Flyway
	implementation 'org.flywaydb:flyway-database-postgresql'

	// AWS S3 操作用
	implementation 'software.amazon.awssdk:s3:2.25.25'
}

tasks.named('test') {
	useJUnitPlatform()
}

bootRun {
	args = ["--spring.profiles.active=local"]
}

test {
	useJUnitPlatform()

	jvmArgs(
			"-XX:+EnableDynamicAgentLoading",
	)

	testLogging {
		showStandardStreams = true
	}
}