services:
  db:
    image: postgres:15
    container_name: portfolio-postgres
#    ports:
#      - "5432:5432"
    env_file:
      - .env.${APP_ENV:-local}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    restart: unless-stopped

  app:
    build:
      context: . # Dockerfileがある現在のディレクトリを指定
      dockerfile: Dockerfile
    container_name: portfolio-app
    ports:
      - "8080:8080" # ホストの8080ポートにアプリの8080ポートを公開
    env_file:
      - .env.${APP_ENV:-local} # DBと同じ環境変数をアプリにも渡す
    depends_on:
      - db # dbサービスが起動してからappサービスを起動
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: portfolio-nginx
    ports:
      - "80:80"    # HTTPをホストに公開
      - "443:443"  # HTTPSをホストに公開
    volumes:
      # 設定ファイルをコンテナにマウント
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-webroot:/var/www/certbot:ro
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - app # アプリ起動後にNginxを起動
    restart: always

  certbot:
    image: certbot/certbot
    container_name: portfolio-certbot
    environment:
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=
    # ports:
    #   - "80:80"
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot

volumes:
  db_data:
  certbot-webroot: