services:
  db:
    image: postgres:15
    container_name: portfolio-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    restart: unless-stopped

  app:
    build:
      context: . # Dockerfileがある現在のディレクトリを指定
      args:
        BUILD_TIMEOUT: 600
      dockerfile: Dockerfile
    container_name: portfolio-app
    depends_on:
      db:
        condition: service_healthy # ★dbがhealthyになるまで待つ
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: portfolio-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: always

volumes:
  db_data: