events { }
http {
    upstream backend {
        server portfolio-app:8080;
    }

    # HTTP (80) - CloudflareからのアクセスをHTTPSへ
    server {
        listen 80;
        server_name portfolio-api.kimuworks.dev;
        return 301 https://$host$request_uri;
    }

    # HTTPS (443) - 自己署名証明書で暗号化維持
    server {
        listen 443 ssl;
        server_name portfolio-api.kimuworks.dev;

        # 証明書のパス（deploy_prod.shで作る場所）
        ssl_certificate     /etc/letsencrypt/live/portfolio-api.kimuworks.dev/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/portfolio-api.kimuworks.dev/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        location ~ ^/(swagger-ui|v3/api-docs) {
            return 404;
        }

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_cookie_path / "/; secure; SameSite=None";
        }
    }
}